### ISSUE TITLE
Slack::Events::Request::InvalidSignature

### ISSUE THREAD

**Issue by icco** [slack-ruby/slack-ruby-bot-server-events#11]
I'm setting up a new app based on https://github.com/slack-ruby/slack-ruby-bot-server-events-app-mentions-sample, and I'm getting `Slack::Events::Request::InvalidSignature`. It's not clear to me how to debug this.

**Comment by icco** [comment]
@CrazyOptimist why closing?

**Comment by CrazyOptimist** [comment]
Sorry, just an accident. I was reading this.

**Comment by icco** [comment]
Actually, this was a typo on my end. Happened because my docker container was deserializing environment variables incorrectly.
