### ISSUE TITLE
Not for Rails Lovers?

### ISSUE THREAD

**Issue by CrazyOptimist** [slack-ruby/slack-ruby-bot-server-events#2]
Thank you so much for your great works!!!
Is it meaningless to use this gem in Rails @dblock ?
Loving Rails soooo much regardless of Ruby lang itself, I really want to dig into the exact implementation of this gem in Rails.
I'm currently using the gem as a Rack app(works fine), but it seems meaningless to use with Rails.
Any advice for it? 👍 🤔

**Comment by dblock** [comment]
This library implements a Grape API, and you can use it with Rails as well. Generally Grape can be mounted on Rails as described [here](https://github.com/ruby-grape/grape#rails).

Did you have to do anything special for Rails? I think we should document using https://github.com/slack-ruby/slack-ruby-bot-server on Rails, and consequently this library. Please feel free to contribute a sample/docs.

**Comment by CrazyOptimist** [comment]
I wish this gem was written for Rails, naming like `slack-bot-server-rails`, `slack-bot-server-events-rails`.
Tried to mount, but leveraging rackup seemed to be more painless, totally modular. I'm doing like that.
Get me more advice if you don't mind.
Thanks!
