### ISSUE TITLE
authorization/security for teams

### ISSUE THREAD

**Issue by alrooney** [slack-ruby/slack-ruby-bot-server-events#24]
It seems currently there is no authorization and I can't figure out how to add authorization cleanly to the SlackRubyBotServer::Api:Endpoints::TeamsEndpoint.  So any user, even if I add authentication, can see all the registered teams and post to any of them i.e. update any of them.  Is there any recommendation in the community about the best way to do this?  Normally I'd add authorization using something like Pundit to replace a call like this:
```teams = Team.all``` 
but the only way I can figure out to do that is to replace that endpoint entirely with my own which I would rather not do.  

Thanks!

**Comment by dblock** [comment]
This is a dup of https://github.com/slack-ruby/slack-ruby-bot-server/issues/171, take a look. Closing it here.

**Comment by alrooney** [comment]
Thanks.  Will check out the other issue.
